CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  email varchar(254) NOT NULL UNIQUE,
  name varchar(250) NOT NULL,

  CONSTRAINT chk_users_name_len
          CHECK (char_length(trim(name))
                 BETWEEN 2 AND 250),
  CONSTRAINT chk_users_email_len
          CHECK (char_length(email)
                 BETWEEN 6 AND 254),
  CONSTRAINT chk_users_email_parts
           CHECK (char_length(split_part(email,'@',1)) <= 64)
);

CREATE TABLE IF NOT EXISTS categories (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
title varchar(120) NOT NULL,
annotation varchar(2000) NOT NULL,
description varchar(7000),
eventDate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
lat  DOUBLE PRECISION NOT NULL,
lon  DOUBLE PRECISION NOT NULL,
paid BOOLEAN NOT NULL,
publishedOn TIMESTAMP WITHOUT TIME ZONE,
createdOn TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
requestModeration BOOLEAN default TRUE,
state varchar(64) NOT NULL,
confirmedRequests BIGINT NOT NULL DEFAULT 0,
participantLimit BIGINT,
category_id BIGINT NOT NULL REFERENCES categories (id),
initiator_id BIGINT NOT NULL REFERENCES users (id),

CONSTRAINT chk_events_title_len
          CHECK (char_length(trim(title))
                 BETWEEN 3 AND 120),
CONSTRAINT chk_events_annotation_len
          CHECK (char_length(annotation)
                 BETWEEN 20 AND 2000),
CONSTRAINT chk_events_description_len
          CHECK (description IS NULL OR char_length(description)
                 BETWEEN 20 AND 7000)
);

CREATE TABLE IF NOT EXISTS requests (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
event_id BIGINT NOT NULL REFERENCES events (id),
requester_id BIGINT NOT NULL REFERENCES users (id),
created TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
status varchar(64) NOT NULL,
CONSTRAINT uniq_request UNIQUE (event_id, requester_id)
);

CREATE TABLE IF NOT EXISTS compilations (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
title varchar(50) NOT NULL UNIQUE,
pinned BOOLEAN default FALSE
);

CREATE TABLE IF NOT EXISTS compilation_events (
compilation_id BIGINT NOT NULL REFERENCES compilations (id) ON DELETE CASCADE,
event_id BIGINT NOT NULL REFERENCES events (id) ON DELETE CASCADE,
PRIMARY KEY (compilation_id, event_id)
);